server:
  port: 8761
spring:
  application:
    name: discovery
  cloud:
    config:
      name: discovery
      import: cloud-config
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
#      discovery:
#        enabled: true
#        service-id: config-server

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka